// Renders a persisted lesson (LessonContent). Pure presentation — no data access.

import { RegulationNote } from "@/components/RegulationNote";
import type { LessonContent } from "@/lib/ai/lesson";

export function LessonView({
  title,
  lesson,
}: {
  title: string;
  lesson: LessonContent;
}) {
  return (
    <article className="space-y-8">
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
        <p className="text-zinc-600 dark:text-zinc-300">{lesson.summary}</p>
        <p className="text-[11px] uppercase tracking-wide text-zinc-400">
          {lesson.generatedBy === "fallback"
            ? "Offline lesson content"
            : `Generated by ${lesson.generatedBy}`}
        </p>
      </header>

      <section>
        <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-zinc-500">
          By the end of this lesson
        </h2>
        <ul className="list-disc space-y-1 pl-5 text-sm text-zinc-700 dark:text-zinc-300">
          {lesson.objectives.map((o) => (
            <li key={o}>{o}</li>
          ))}
        </ul>
      </section>

      <div className="space-y-6">
        {lesson.sections.map((s) => (
          <section key={s.heading} className="space-y-2">
            <h2 className="text-lg font-medium">{s.heading}</h2>
            {s.body.split(/\n{2,}/).map((para, i) => (
              <p key={i} className="text-zinc-700 dark:text-zinc-300">
                {para}
              </p>
            ))}
          </section>
        ))}
      </div>

      <section className="rounded-xl border border-black/10 bg-zinc-50 p-4 dark:border-white/15 dark:bg-zinc-900/50">
        <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-zinc-500">
          Worked example
        </h2>
        <p className="font-medium text-zinc-800 dark:text-zinc-200">
          {lesson.worked_example.prompt}
        </p>
        <p className="mt-2 whitespace-pre-line text-zinc-700 dark:text-zinc-300">
          {lesson.worked_example.solution}
        </p>
      </section>

      <section>
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-zinc-500">
          Practice (check yourself)
        </h2>
        <ol className="space-y-3">
          {lesson.practice.map((p, i) => (
            <li
              key={i}
              className="rounded-lg border border-black/10 p-3 text-sm dark:border-white/15"
            >
              <p className="font-medium text-zinc-800 dark:text-zinc-200">{p.prompt}</p>
              <details className="mt-2 text-zinc-600 dark:text-zinc-400">
                <summary className="cursor-pointer select-none text-violet-600 dark:text-violet-400">
                  Show answer
                </summary>
                <p className="mt-1">
                  <span className="font-semibold">Answer:</span> {p.answer}
                </p>
                <p className="mt-1">{p.explanation}</p>
              </details>
            </li>
          ))}
        </ol>
      </section>

      <section>
        <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-zinc-500">
          Key terms
        </h2>
        <dl className="space-y-1 text-sm">
          {lesson.key_terms.map((t) => (
            <div key={t.term} className="flex gap-2">
              <dt className="font-semibold text-zinc-800 dark:text-zinc-200">{t.term}:</dt>
              <dd className="text-zinc-600 dark:text-zinc-400">{t.definition}</dd>
            </div>
          ))}
        </dl>
      </section>

      {lesson.regulationNote ? <RegulationNote>{lesson.regulationNote}</RegulationNote> : null}
    </article>
  );
}
