// Parental consent for minors (Law 25 — T36 schema, T37 flow).
//
// consent_records (migration 0011) is append-only: every decision is a new row.
// "Active" consent for a child = the most recent row for the CURRENT version
// with granted = true. Bump CONSENT_VERSION whenever a purpose below changes
// materially — old rows then no longer count as active and the guardian is
// re-prompted.

import { getServiceClient } from "@/lib/db";

/** Current consent version. Bump on any material change to CONSENT_PURPOSES. */
export const CONSENT_VERSION = "2026-09";

/**
 * The specific purposes a guardian consents to. Shown verbatim on the consent
 * screen; stored on the record so we can prove what was agreed to.
 */
export const CONSENT_PURPOSES = [
  {
    key: "curriculum",
    label: "Deliver the curriculum and record my child's progress",
    detail:
      "Lessons, checkpoints, unit assessments and term exams, and the results for each.",
  },
  {
    key: "ai_instruction",
    label: "Use AI to generate the lessons and assessments",
    detail:
      "Course content is generated by a third-party model (Anthropic). Most requests carry only course text; the volunteer handoff briefing carries my child's first name and progress signals. Grading is done by fixed program logic, not the model.",
  },
  {
    key: "compliance_record",
    label: "Use the results to assemble a home-instruction progress record",
    detail:
      "Suffa organises the evidence; I remain responsible for filing it with the ministère de l'Éducation.",
  },
  {
    key: "retention",
    label: "Keep this data for the stated retention period",
    detail:
      "Account and learning data are kept while enrolled and for a limited period after; free-text session notes are kept for a shorter window. See the Privacy Policy.",
  },
] as const;

export type ConsentPurposeKey = (typeof CONSENT_PURPOSES)[number]["key"];

export const ALL_CONSENT_PURPOSE_KEYS: ConsentPurposeKey[] = CONSENT_PURPOSES.map(
  (p) => p.key,
);

export interface ConsentRecord {
  id: string;
  studentUserId: string;
  guardianUserId: string;
  version: string;
  purposes: string[];
  granted: boolean;
  recordedAt: string;
}

function shape(r: Record<string, unknown>): ConsentRecord {
  return {
    id: r.id as string,
    studentUserId: r.student_user_id as string,
    guardianUserId: r.guardian_user_id as string,
    version: r.consent_version as string,
    purposes: (r.purposes as string[] | null) ?? [],
    granted: Boolean(r.granted),
    recordedAt: r.recorded_at as string,
  };
}

/** Append one consent decision (grant or withdrawal). Tenant-guarded by caller. */
export async function recordConsentDecision(input: {
  masjidId: string;
  studentUserId: string;
  guardianUserId: string;
  granted: boolean;
  purposes: readonly string[];
  documentHash?: string;
}): Promise<void> {
  const { error } = await getServiceClient()
    .from("consent_records")
    .insert({
      masjid_id: input.masjidId,
      student_user_id: input.studentUserId,
      guardian_user_id: input.guardianUserId,
      consent_version: CONSENT_VERSION,
      purposes: [...input.purposes],
      granted: input.granted,
      document_hash: input.documentHash ?? null,
    });
  if (error) throw new Error(`recordConsentDecision: ${error.message}`);
}

/** Every consent decision for a child, newest first. Tenant-guarded by caller. */
export async function listConsentRecords(
  studentUserId: string,
  masjidId: string,
): Promise<ConsentRecord[]> {
  const { data, error } = await getServiceClient()
    .from("consent_records")
    .select("*")
    .eq("masjid_id", masjidId)
    .eq("student_user_id", studentUserId)
    .order("recorded_at", { ascending: false });
  if (error) throw new Error(`listConsentRecords: ${error.message}`);
  return (data ?? []).map((r) => shape(r as Record<string, unknown>));
}

/**
 * The active consent for a child: the most recent decision for the CURRENT
 * version. Returns null if there is none, or if the latest decision for this
 * version is a withdrawal.
 */
export async function getActiveConsent(
  studentUserId: string,
  masjidId: string,
): Promise<ConsentRecord | null> {
  const records = await listConsentRecords(studentUserId, masjidId);
  const latestForVersion = records.find((r) => r.version === CONSENT_VERSION);
  if (!latestForVersion || !latestForVersion.granted) return null;
  return latestForVersion;
}

/** True when a child has current, un-withdrawn guardian consent. */
export async function hasActiveConsent(
  studentUserId: string,
  masjidId: string,
): Promise<boolean> {
  return (await getActiveConsent(studentUserId, masjidId)) !== null;
}
